### ISSUE TITLE
Breaks JSLint refresh

### ISSUE THREAD

**Issue by sixertoy** [phoenix3008/brackets-phplinter#2]
Hey :)

To reproduce:
move extensionfrom "user"  to "disabled" etension's folder
open an js file create a jslint warn
close brackets
open brackets
open jslint panel
fix jslint error
save
-> jslint panel will close
ctrl + z
-> jslint will pop
close brackets
move extension from "disabled" to "user" etension's folder
open brackets
-> jslint warn error
change project
return to previous project
fix error
save
-> jslint panel won't close

I'll try to fix it, i thing it's a breaking chain on save action

++

**Comment by sixertoy** [comment]
commenting DocumentManager.off('documentSaved'); @line 39 seems to fix it
Due to my fault...

A quick would be
DocumentManager.off('documentSaved', analizeErrorsCall);

I let you see by your own how to fix it as clean as it clean be

Thx

**Comment by FrancescoBorzi** [comment]
I can confirm, this plugin breaks my JSLint too.
